### ISSUE TITLE
Uncaught error with bad yaml

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#151]
I ran with this course and I received an unhandled error that doesn't show up in debug:

```
namespace: infra
repository: stable
context: pzlomxv9.test-infra.hillghost.com
repositories:
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
minimum_versions:
  helm: 2.14.3
  reckoner: 2.1.0
charts:
  prometheus-operator:
    namespace: prometheus-operator
    hooks:
      pre_install:
        - kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.32/example/prometheus-operator-crd/alertmanager.crd.yaml
        - kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.32/example/prometheus-operator-crd/prometheus.crd.yaml
        - kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.32/example/prometheus-operator-crd/prometheusrule.crd.yaml
        - kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.32/example/prometheus-operator-crd/servicemonitor.crd.yaml
        - kubectl apply -f https://raw.githubusercontent.com/coreos/prometheus-operator/release-0.32/example/prometheus-operator-crd/podmonitor.crd.yaml
     repository: stable
     version: 6.21.0
    values:
      prometheusOperator.createCustomResource: false
      prometheusOperator.admissionWebhooks.enabled: false
```

CLI
```
└─ reckoner --log-level=DEBUG plot prometheus-course.yml
⛵🔥 Encountered unexpected error in Reckoner! Run with --log-level debug to see details! ⛵🔥
```

note that this is not valid yaml since the repository and version are improperly indented.
