### ISSUE TITLE
Reckoner fails to install chart - might be user error

### ISSUE THREAD

**Issue by clanstyles** [FairwindsOps/reckoner#152]
```
namespace: infrastructure
repositories:
  postgres:
    git: https://github.com/zalando/postgres-operator
    path: charts

charts:
########################################
##  POSTGRES OPERATOR
########################################
  postgres-operator:
    namespace: infrastructure
    repository: postgres
    chart: postgres-operator
```

The directory it's in is in charts. If you try charts/postgres-operator it still fails.

```
2019-10-24 16:58:39 desktop root[28474] WARNING Cmd('git') failed due to: exit code(1)
  cmdline: git checkout master
  stderr: 'error: Sparse checkout leaves no entry on working directory'
2019-10-24 16:58:39 desktop root[28474] WARNING Error with path "charts"! Remove path when chart exists at the repository root
2019-10-24 16:58:39 desktop root[28474] WARNING Skipping chart None
```

**Comment by sudermanjr** [comment]
For some reason it seems like the git stuff doesn't work at the top level.  I was able to make this work:

```
namespace: infrastructure
repositories:
  incubator:
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
charts:
########################################
##  POSTGRES OPERATOR
########################################
  postgres-operator:
    namespace: infrastructure
    repository:
      git: https://github.com/zalando/postgres-operator
      path: charts
    chart: postgres-operator
```

**Comment by clanstyles** [comment]
@sudermanjr getting further! Still doesn't seem to work.

```
Stopping chart installations due to an error! Some of your charts may not have been installed!
⛵🔥 Encountered errors while running the course ⛵🔥

* * * * *

Chart Name: postgres-operator
Status: Failed
Error Reason: Command Failed with output below:
STDOUT: Release "postgres-operator" does not exist. Installing it now.
```

**Comment by endzyme** [comment]
Thanks for the issue @clanstyles - we can dig into this. Sorry this tripped you up - I'll see if I can recreate on my end

What version of: Helm, Kubernetes and Reckoner are you using?

**Comment by sudermanjr** [comment]
@clanstyles you may need to `helm delete --purge postgres-operator` before running again.

**Comment by endzyme** [comment]
Cool - so I found the issue @clanstyles. It's definitely a bug with git repos in the main course root spec. I will make a PR today but there are some other implications/considerations. A refactor of the repository class is required to really get to the bottom of the issue but there is a fix that has a fairly simple stipulation (and won't require refactoring the schema). 

If you have a git based repository in the main root of the course, it _requires_ that the "name" of the repository matches the folder name in the repo. As an interesting note, chart git repositories with charts in the root of the repo do _not_ need to have a special consideration for the repo name. I'll outline working and non-working examples below and the contributing reasons there is the initial issue.

Thanks again and we're really sorry you hit this issue! I'll be posting a PR fix for this, but it will still require the stipulations that your `repositories:` name will have to match the folder that holds your actual chart.

working example:
```yaml
namespace: infrastructure
repositories:
  postgres-operator: # this *has* to be postgres-operator since the github repo chart lives in ./charts/postgres-operator
    git: https://github.com/zalando/postgres-operator
    path: charts
  canbeanything: # this can be set to any string since it isn't using sparse checkout for checking out a specific folder
    git: https://github.com/goharbor/harbor-helm.git
charts:
  postgres-operator:
    namespace: infrastructure
    repository:
      git: https://github.com/zalando/postgres-operator
      path: charts
    chart: postgres-operator
  goharbor:
    repository: canbeanything
```

**Comment by endzyme** [comment]
Below is the historical info for people who will be fixing this long term.

Originally this class was implemented to support "sparse checkout" in git, so that the checkout didn't have to check out the entire repository via git, only a small subset. The implementation wasn't very well documented on what fields in the course.yml schema affect how git repos work. In order to fix this I would definitely consider potential changes to the schema for repository/repositories in course.yml. Currently, the key of the root `repositories: {}` section in course.yml acts as the name for the repo listed in `helm repo list` as well as has overlap with how git checkouts work. When defined in root `repositories: {}` the code implementation doesn't have the concept of a "chart name", which is different than when listing the repository in the `charts: {}` section of the course.yml. Additionally, there is a lack of clarity on which fields are directly tied to file-system folders when cloning repos from a git endpoint. One other conflicting implementation is how the root `repositories: {}` is used; The repositories at the top of the course are intended to be used as reference, since generally helm-repositories hold many charts. Unfortunately when you define a git based chart repository it really only supports one chart, since the spec requires a singular path to checkout via git. This means, if you have a git repo with many charts, you have to make a course repositories entry for _each specific chart_ while duplicating the repository git information. This isn't ideal for sure and has other implications.

**Comment by endzyme** [comment]
As an FYI - I think this PR has been able to resolve the requirement of using the "chart folder name" as the key to the `repositories: {}` block. Below are examples of working configs:

```yaml
namespace: example-infrastructure
repositories:
  some-repo:
    git: https://github.com/zalando/postgres-operator
    path: charts
charts:
  my-postgres-operator:
    namespace: infrastructure
    repository: some-repo
    chart: postgres-operator
  goarbor:
    repository:
      git: https://github.com/goharbor/harbor-helm.git
  nginx:
    chart: nginx-ingress
    repository: stable
```
