### ISSUE TITLE
attempting to parse env vars inside comments 

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#173]
Looks like we may have a regression. 

https://github.com/FairwindsOps/reckoner/issues/150

**Comment by sudermanjr** [comment]
This snippet:

```
  letsencrypt-setup:
    chart: letsencrypt-setup
    version: v2.0.1
    repository:
      name: fairwinds-incubator
    values:
      clusterIssuers:
        primary:
          enabled: true
          clusterIssuerName: letsencrypt-prod
          email: andy@fairwinds.com
          solvers:
            http:
              enabled: false
            dns:
            - type: route53
                # accessKeyID: "${AWS_ACCESS_KEY}" optionally specify IAM access key
                # secretName: "${AWS_K8S_SECRET_NAME}" required if accesKeyID is set
                # secretKey: "${AWS_K8S_SECRET_KEY}" required if accesKeyID is set
                # role: ${IAM_ROLE} required if hosts don't have IAM roles AND accessKeyID, secretName, secretKey are not set
              hostedZoneID: Z1IOP6USK5ATWU
              region: us-east-2
                # The selector section is optional and only should be necessary if you need to provide certs for multiple domains
                # selector:
                #   dnsZones:
                #   - example.com
            # - type: cloudflare
            #   secretName: cloudflare-auth
            #   secretKey: api-key
            #   email: "${CF_EMAIL}"
            #   selector: {}
            # - type: clouddns
            #   project: test-project
            #   selector:
            #     dnsNames:
            #       - api.example.com
        selfsigned:
          enabled: false
          clusterIssuerName: letsencrypt-selfsigned
          email: andy@fairwinds.com
          solvers:
            http:
              enabled: false
              # If you want http checking to work on any ingress using shim, the ingressName or ingressClass is not necessary
              # ingressName: "${LE_INGRESS_SHIM_NAME}"
              # ingressClass: ${LE_INGRESS_CLASS}
```

Caused this error: 

```
* * * * *
Chart Name: letsencrypt-setup
Status: Failed
Error Reason: Missing required environment variable: AWS_ACCESS_KEY
* * * * *
```
