### ISSUE TITLE
Make repository path relative to yaml file

### ISSUE THREAD

**Issue by elthariel** [FairwindsOps/reckoner#248]
Imagine a folder structure like this one:

```
charts/
  my-chart/
    [...]
  dev/
    plot.yml
  prod:
    plot.yml
```

If in dev/plot.yml, you have

```yaml
charts:
  my-chart:
    chart: my-chart
    repository: ../charts
```

and you run reckoner from the top-level folder, it won't find the chart folders. i.e. when using a path to specify the repository, this path is not relative to the reckoner file. I think it should. WDYT ?
