### ISSUE TITLE
Proposal: V2 `course.yml` format

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#267]
The current format makes extensive use of dictionary yaml structures for the main sections `repositories` and `charts`
I propose a format change that make these list yaml structures instead, further, I propose an update to terminology, shifting `charts` -> `releases`

So a course:
```
namespace: kube-system
namespace_management:
  default:
    metadata:
      annotations:
        ManagedBy: com.fairwinds.reckoner
      labels:
        labelName: labelValue
    settings:
      overwrite: True
context: my-kube-cluster
repositories:
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
hooks:
  pre_install:
    - ls ./
  post_install:
    - kubectl get namespaces
charts:
  my-metrics-server: # See below for chart schema
    repository: stable
    chart: metrics-server
 ```
 may, instead be structured
 ```
---
version: 2
namespace: kube-system
namespace_management:
  default:
    metadata:
      annotations:
        ManagedBy: com.fairwinds.reckoner
      labels:
        labelName: labelValue
    settings:
      overwrite: True
context: my-kube-cluster
repositories:
- name:  stable
   url: https://kubernetes-charts.storage.googleapis.com
hooks:
  pre_install:
    - ls ./
  post_install:
    - kubectl get namespaces
releases:
- name:my-metrics-server: # See below for chart schema
   repository: stable
   chart: metrics-server
 ```
 
 The reason for this proposed change is to:
* enable a better structure data format for future work (whispers in struct)
* allows more flexible deployment and use of helm3, (you can use the same release name across namespaces)
* more accurate terminology for what the reckoner manages. It does not manage charts after all, it manages releases
