### ISSUE TITLE
Proposal: Expanded Secrets Capability

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#268]
The current support for values that may be secret is only through environment variables. 
I propose secret backend functionality where by Reckoner would accept some secret metadata and retrieve the secret from a back end such as vault or parameter store. 

Two potential schema changes for this come to mind. 
First, a new chart or course level key that would contain the metadata ala:
```yaml
secrets:
- backend: ParameterStore
  path: /my/very/important/value
  region: us-west-2
  var: DATADOG_API_KEY
charts:
  chartone:
    secrets:
    - backend: Vault
      path: /not/as/important/value
      url: https://vault.com
      var: DATADOG_APP_KEY
```
Where `${DATADOG_API_KEY}` and `${DATADOG_APP_KEY}` would be replaced in the course in the same way environment variables are

OR with inline metadata
```
charts:
  charttwo:
    values:
        fancySecret: secret:AWSSSM::us-west-2:/my/very/important/value
```

Or some such. I think the first version is potentially more versatile but complex to implement.  It could utilize exising `String.Template()` code though.
