### ISSUE TITLE
Yaml with comments in multiline Yaml blocks broken

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#270]
This is pretty specific and easily worked around but thought it should be tracked.
Given Course Snippet:
```yaml
charts :
  es-curator:
    chart: curator
    repository: ../../charts/elasticsearch
    namespace: prod
    values:
      image:
        pullPolicy: IfNotPresent
      configMaps:
          # Having config_yaml WILL override the other config
        config_yml: |-
          client:
            hosts:
              - http://esc.prod.wtf.sh
            port: 80
            use_ssl: False
            # Any comment in here breaks it
```
The output from the `reckoner template` (and `plot` and `update`) ends up with 
`config.yml:   "client:\n  hosts:\n    - http://esc.prod.wtf.sh\n  port: 80\n  use_ssl: False\n  \n"`
Where `config_yml` is the data for `config.yml` 

Whereas, as long as there are no comments in the yaml block in the multi line yaml section (see below) the output is expected. 
```yaml
charts :
  es-curator:
    chart: curator
    repository: ../../charts/elasticsearch
    namespace: prod
    values:
      image:
        pullPolicy: IfNotPresent
      configMaps:
          # Having config_yaml WILL override the other config
        config_yml: |-
          client:
            hosts:
              - http://esc.prod.wtf.sh
            port: 80
            use_ssl: False
```

At first glance it appears to be with the code that pull the `values` into a file, then reads the file as yaml to do the variable interpolation on environment variables. It drops the comments (probably not desired behavior) but seems to leave extra `\n` which may, or may not, be an issue. 

Easy work arounds include:
* remove comments from the multiline yaml block
* use a values file external to the `course.yml` file
