### ISSUE TITLE
Hidden Error  when `context` is used with `diff`  and context does not exist in`$KUBECONFIG`

### ISSUE THREAD

**Issue by ejether** [FairwindsOps/reckoner#273]
Given a course:
```
---
_references: {}
namespace: kube-system
repository: stable
context: prod
repositories:
  incubator:
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  stable:
    url: https://kubernetes-charts.storage.googleapis.com
hooks: {}
charts:  ...
```

and a KubeConfig

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <redacted>
    server: <redacted>
  name: <redacted>
contexts:
- context:
    cluster: <redacted>
    user: <redacted>
  name: production-cluster
current-context: production-clusters
kind: Config
preferences: {}
...
```

where the `context` "prod" in the `course.yml` does not exist in the `$KUBECONFIG`, the `helm get manifests  --namespace kube-sytem --context prod` silently fails. It only logs to the debug level and the error does not stop the run.

As a result when the `helm template --namespace kube-system --context prod` (which does not need or use the namespace and context flags) proceeds and succeeds, there is an apparent large diff.

***The error in `helm get manifests` should halt execution***

cc: @caroll2695
