### ISSUE TITLE
Support for float values

### ISSUE THREAD

**Issue by bjaworski3** [FairwindsOps/reckoner#47]
Floating point values get cast into strings. This breaks some helm charts that expect them to be floats.

Example reckoner settings:
```
kubespawner_override:
   cpu_limit: 0.5
   mem_limit: 512
```

Error from app on the cpu_limit type: 
`Error: the 'cpu_limit' trait of KubeSpawner instance must be a float, but a value of '0.5' <class 'str'> was specified`

**Comment by ejether** [comment]
Interesting. 
Would you provide an example chart that causes this error, please?

**Comment by bjaworski3** [comment]
I'm using this helm chart: https://jupyterhub.github.io/helm-chart/

Here's the full config (with sensitive info changed):
```
jupyterhub:
    repository: jupyterhub
    namespace: jupyterhub
    version: 0.8-68b9a91
    values:
      proxy.secretToken: random_generated_token
      ingress.enabled: true
      ingress.hosts[0]: jupyterhub.example.com
      ingress.tls[0].hosts[0]: jupyterhub.example.com
      singleuser:
        image:
          name: jupyter/datascience-notebook
          tag: 14fdfbf9cfc1
        profileList:
          - display_name: "Minimal environment"
            description: "Minimal resources for testing basic scripts"
            default: true
            kubespawner_override:
              cpu_guarantee: 0.5
              cpu_limit: 0.5
              mem_guarantee: 512
              mem_limit: 512
          - display_name: "Datascience environment"
            description: "Full datascience environment"
            kubespawner_override:
              cpu_guarantee: 2
              cpu_limit: 2
              mem_guarantee: 2048
              mem_limit: 2048
```
