### ISSUE TITLE
Variables not evaluated when using `files` command

### ISSUE THREAD

**Issue by Azahorscak** [FairwindsOps/reckoner#487]
When passing values in with the `files` functionality, environment variables are not expanded. 

For example/to recreate: if this block is added directly to the course.yaml the variables are replaced with their values correctly.
```
datadog:
        confd:
          postgres.yaml: |-
                  instances:
                    - host: "${PG_HOST}"
                      port: 4666
                      username: "${DB_USER}"
                      password: "${DB_PASSWORD}"
```

But when the exact same block is placed in a separate file and passed in with the `files` directive, the literal values ie."${DB_USER}", "${DB_PASSWORD}" are passed to the chart.
