### ISSUE TITLE
[Go version] Support file-based value files

### ISSUE THREAD

**Issue by lucasreed** [FairwindsOps/reckoner#527]
**Is your feature request related to a problem? Please describe.**
Should support parsing files (most likely being done in the python version by passing `--values <file_path/file_name` to the helm command utilized) as values files like so in the course.yml file:

```
charts:
  chart-one:
    repository: fairwinds-incubator
    chart: basic-demo
    files:
      - subfolder/yaml_values.yml
```
