### ISSUE TITLE
Reckoner import feature

### ISSUE THREAD

**Issue by endzyme** [FairwindsOps/reckoner#53]
It would be awesome if reckoner had a command to import a repository chart and build the correct yaml format for me.

Example

```bash
# all params used
reckoner import foo/datadog --version v0.0.1 --repository foo/https://your.repo/charts --name my-datadog <course.yml>

# defaults to whatever repo is in course.yml for "stable" and loads the latest version as --version
reckoner import stable/cert-manager
```

```yaml
# expected output
  my-datadog:
    chart: datadog
    repository: stable
    version: v0.0.1
```

Features
* Validate the repo, chart and version exist
* Leverage the course.yml 

MVP
* Instead of modifying your course.yml maybe stdout the yaml sections
* If we could save comments and alignment then we could just write to the course.yml directly

Stretch
* Leverage defaults for desired default values settings `reckoner import stable/cert-manager --default-values=https://my.url.com/charts/_my_defaults.yml`
