### ISSUE TITLE
[go] Cannot escape $ like in python version

### ISSUE THREAD

**Issue by sudermanjr** [FairwindsOps/reckoner#558]
### What happened?

```
4s ✗ ~/go/src/github.com/fairwindsops/reckoner/reckoner-go template course.yml -a -v3

I0330 13:42:06.692266   83829 validation.go:45] colorize output: true
ERROR: environment variable $ is not set
ERROR: environment variable $ is not set
I0330 13:42:06.697639   83829 course.go:348] failed to unmarshal file: course has env variables that are not properly set
Course file has schema validation errors - error opening course file course.yml: Course file has schema validation errors
```

### What did you expect to happen?

There are times when a literal `$` is needed. In the python version, this was escaped using `$$`, but this does not seem to work in the golang version.

### How can we reproduce this?

Create a course file with an entry like:

```
  goldilocks:
    chart: goldilocks
    namespace: goldilocks
    version: 5.3.0
    repository: fairwinds-stable
    values:
      controller:
        enabled: true
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 50m
      dashboard:
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx-ingress
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/auth-signin: https://auth.ops.fairwinds.com/oauth2/start?rd=https://$$host$$request_uri
            nginx.ingress.kubernetes.io/auth-url: https://auth.ops.fairwinds.com/oauth2/auth
          hosts:
          - host: goldilocks.ops.fairwinds.com
            paths:
              - path: /
                type: ImplementationSpecific
          tls:
          - secretName: goldilocks-tls
            hosts:
            - goldilocks.ops.fairwinds.com
```

### Version

master branch - golang version

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
