### ISSUE TITLE
Reckoner 6.0.0-rc4 does not interpolate environment variables in release values

### ISSUE THREAD

**Issue by ivanfetch-fw** [FairwindsOps/reckoner#575]
### What happened?

The Helm release shows `$VariableName` in values, instead of the value of sed environment variable.

### What did you expect to happen?

The value of the environment variable should be reflected in the Helm values.

### How can we reproduce this?

Using this Course:
```yaml
schema: v2
namespace: test
repositories:
  fairwinds-stable:
    url: https://charts.fairwinds.com/stable
namespace_management:
  default:
    settings:
      overwrite: false
releases:
  - name: rbac-manager
    namespace: rbac-manager
    namespace_management:
      settings:
        overwrite: false
    chart: rbac-manager
    version: 1.11.0
    repository: fairwinds-stable
    values:
      pointless: $INSIGHTS_URI
```

The `INSIGHTS_URI` environment variable is set to something:
```bash
$ echo $INSIGHTS_URI
https://xxxxx.k8s.insights.fairwinds.com
```

After `reckoner plot -a test.yaml`, looking at the helm values for brac-manager shows the name of the environment variable, not its value:
```bash
helm get values -n rbac-manager rbac-manager
USER-SUPPLIED VALUES:
pointless: $INSIGHTS_URI
```

### Version

Version:6.0.0-rc.4 Commit:a163b28e538952188d12186b4f8a8562cc365708

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
