### ISSUE TITLE
Clarify the usage of secrets - replace helm values by secrets ?

### ISSUE THREAD

**Issue by Startouf** [FairwindsOps/reckoner#651]
Hello,
when reading your readme and instructions on the website, it's not clear how to use your "secrets" in the charts/container

The issue https://github.com/FairwindsOps/reckoner/issues/268 and PR https://github.com/FairwindsOps/reckoner/pull/271 seems to hint that secrets are made available as os.environ, does that mean they are injected as ENV variables for all running containers / all pods, services, etc ?

Is it possible to instead replace a value by a secret ? I often find helm charts that expect the secret value to be directly injected like in a value `env.SECRET_KEY` but it can be something else `submodule.something.SECRET_KEY`

It would be great to have something like

```
secrets:
- backend: ParameterStore
  path: /my/very/important/value
  region: us-west-2
  name: API_KEY
charts:
  my_chart:
    secrets:
      - name: API_KEY
        injectAsValue: path.in.values.file # like worker.slack.CLIENT_SECRET
```

Some charts like bitnami already provide an `existingSecret` value, and sometimes we can even customize the name of the keys to be used. 

But maybe I've been misunderstanding something from the start regarding how secrets work ? I would like to be able to add secrets to any chart I could find on the internet when deployed via a reckoner core.yaml file (and commit the core.yml file without any secret key inside)

**Comment by sudermanjr** [comment]
Because Reckoner parses environment variables, you can reference an injected secret by using `$API_KEY` in your example, wherever you want to put it. If I'm understanding your example correctly, something along the lines of

```
secrets:
- backend: ParameterStore
  path: /my/very/important/value
  region: us-west-2
  name: API_KEY
charts:
  my_chart:
    values:
      path-to-secret-value: "$API_KEY"
```

As far as more enhanced secrets capabilities, It would be interesting to support creating a Kubernetes Secret, but we don't have any plans to do that. You could use a hook to create one from an env var with a `kubectl create secret generic --from-literal $API_KEY` if you wanted to do that.

**Comment by Startouf** [comment]
As discussed in https://fairwindscommunity.slack.com/archives/CUT9Z11ND/p1670578610834919 the appropriate syntax to retrieve an existing secret is this one (thanks Andy)
```
secrets:
  - name: AWS_ACCESS_KEY_ID
    backend: ShellExecutor
    script:
      - bash
      - -c
      - |
        #!/bin/bash
        kubectl get secret --namespace my-namespace my-secrets -o jsonpath='{.data.access-key-id}' | base64 --decode
        
charts:
  my-chart:
    namespace: my-namespace
    chart: my-chart
    repository: ../../charts
    values:
      env:
        ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
  ```

Are the docs generated by this repo as well ? should I make a PR to add this use case somewhere in the docs ?
