### ISSUE TITLE
basic template error

### ISSUE THREAD

**Issue by rosscdh** [FairwindsOps/reckoner#668]
### What happened?

Tried to use the example course.yaml from the documentation

did a go install and hen followed help output

```
reckoner template course.yaml --output-dir /tmp --run-all
panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/fairwindsops/reckoner/pkg/course.convertV1toV2({0x105a29d73, 0xb})
	/Users/rcrawford/p/poc/hafen/reckoner/pkg/course/course.go:283 +0x3f4
github.com/fairwindsops/reckoner/pkg/course.OpenCourseFile({0x105a29d73, 0xb}, {0x106c629a0, 0x1aea, 0x1aea})
	/Users/rcrawford/p/poc/hafen/reckoner/pkg/course/course.go:316 +0x88
github.com/fairwindsops/reckoner/pkg/reckoner.(*Client).Init(0x140003d2c80, {0x105a29d73, 0xb}, 0x0)
	/Users/rcrawford/p/poc/hafen/reckoner/pkg/reckoner/client.go:75 +0x50
github.com/fairwindsops/reckoner/cmd.glob..func3(0x106ca9f60?, {0x140000b1260?, 0x0?, 0x3?})
	/Users/rcrawford/p/poc/hafen/reckoner/cmd/root.go:166 +0x19c
github.com/spf13/cobra.(*Command).execute(0x106ca9f60, {0x140000b0a80, 0x3, 0x3})
	/Users/rcrawford/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x5b0
github.com/spf13/cobra.(*Command).ExecuteC(0x106ca96c0)
	/Users/rcrawford/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x35c
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/rcrawford/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/fairwindsops/reckoner/cmd.Execute({0x105a235cb?, 0x1049dbb44?}, {0x105a22b1c?, 0x0?}, {0x106c629a0?, 0x1049dbb4c?, 0x5d749c0?})
	/Users/rcrawford/p/poc/hafen/reckoner/cmd/root.go:400 +0xf4
main.main()
	/Users/rcrawford/p/poc/hafen/reckoner/main.go:31 +0x50
```

### What did you expect to happen?

template should have been rendered to output folder

### How can we reproduce this?

commands provided above

### Version

 reckoner version Version:0.0.0 Commit:n/a

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rosscdh** [comment]
Great idea hoping to make use of it

**Comment by rosscdh** [comment]
I then removed the polaris reference and got
```
reckoner template course.yaml --output-dir /tmp --run-all
WARNING: this course file was automatically converted from v1 to v2 at runtime - to convert the file permanently, run "reckoner convert -i course.yaml"
```

```
namespace: default
charts:
  grafana:
    namespace: grafana
    values:
      image:
        tag: "6.2.5"
  # polaris-dashboard:
  #   namespace: polaris-dashboard
  #   repository:
  #     git: https://github.com/FairwindsOps/charts
  #     path: stable
  #   chart: polaris

```

looks like a docs issue :)

**Comment by rosscdh** [comment]
```
schema: v2
namespace: default
namespace_management:
  default:
    settings:
      overwrite: false
releases:
  - name: grafana
    namespace: grafana
    namespace_management:
      settings:
        overwrite: false
    chart: grafana
    repository: ""
    values:
      image:
        tag: 6.2.5

```

**Comment by rosscdh** [comment]
hmm but no templates are rendered
```
 tree /tmp/junk/
/tmp/junk/
└── grafana

2 directories, 0 files
```

**Comment by rosscdh** [comment]
also with latest release

```
~/Downloads/reckoner_6.1.0-rc.3_darwin_amd64/reckoner template course.yaml --output-dir /tmp/junk --run-all -v 5
I0219 19:14:33.139399   34307 validation.go:43] colorize output: true
I0219 19:14:33.140369   34307 course.go:533] no default repository set - skipping filling out defaults
I0219 19:14:33.143224   34307 helm.go:38] found helm at /opt/homebrew/bin/helm
I0219 19:14:33.143468   34307 client.go:142] no minimum helm version found, assuming okay
I0219 19:14:33.143480   34307 client.go:164] checking current reckoner version: 6.1.0-rc.3
I0219 19:14:33.143486   34307 client.go:166] no minimum reckoner version found, assuming okay
```

**Comment by rosscdh** [comment]
hmm ok looks like its the v1 grafana chart reference.. the tests work

```
reckoner template reckoner/end_to_end_testing/course_files/20_test_strong_ordering.yaml -a -v 5

            runAsUser: 1200
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              cpu: 70m
              memory: 131072k
            requests:
              cpu: 10m
              memory: 131072k
---
# Source: basic-demo/templates/hpa.yaml
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: second-chart-basic-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: second-chart-basic-demo
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60
```

Looks like jsut a bit more error catching
