### ISSUE TITLE
Using diff with an unexisting chart version shows no difference

### ISSUE THREAD

**Issue by lmo-wt** [FairwindsOps/reckoner#670]
### What happened?

When using `reckoner diff` on a release using a chart version that does not exist, reckoner shows no difference.

### What did you expect to happen?

Reckoner should trigger an error or at least an information message.

### How can we reproduce this?

Using this basic sonarqube configuration file, `reckoner diff <file> -o sonarqube` will show no difference.

```
schema: v2
namespace: sonarqube

repositories:
  sonarqube:
    url: https://SonarSource.github.io/helm-chart-sonarqube

minimum_versions:
  helm: 3.0.0
  reckoner: 6.0.0

releases:
  - name: sonarqube
    namespace: sonarqube
    chart: sonarqube
    version: i.do.not.exist
    repository: sonarqube
```

### Version

6.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
