### ISSUE TITLE
Can't use $ in strings as expected in reckoner 6

### ISSUE THREAD

**Issue by Azahorscak** [FairwindsOps/reckoner#678]
### What happened?

When passing in a string with `$`'s in them i'm unable to escape the $ as expected. 
This fails with the following message. 
```I0306 12:04:50.004956   22868 course.go:353] failed to unmarshal file: course has env variables that are not properly set
Course file has schema validation errors - error opening course file course.yml: Course file has schema validation errors
```

### What did you expect to happen?

The string to be treated the same as in reckoner 5 and the diff command to succeed.

### How can we reproduce this?

You can include a string in the course file that has a $ in the value. 

- name: EXAMPLE_VAR
   value: 'example$var'

### Version

6.0.0

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sudermanjr** [comment]
In your example to reproduce the issue, you only have a single $. Have you tried `example$$var` ?

**Comment by sudermanjr** [comment]
I still cannot reproduce the error. Can you please try with the latest RC of 6.1.0?

```
 SECRET_TEST='foo$foo' reckoner template /tmp/course.yaml -a
 ```
 
 
 ```
---
_references: {}
namespace: infra
repository: stable
context: DONOTUSE
helm_args:
- --skip-tests
- --include-crds
repositories:
  fairwinds-stable:
    url: https://charts.fairwinds.com/stable
  fairwinds-incubator:
    url: https://charts.fairwinds.com/incubator
charts:
  vpa:
    chart: vpa
    namespace: vpa
    version: 1.2.2
    repository: fairwinds-stable
    values:
      env:
        - name: FOO
          value: "$SECRET_TEST"
      recommender:
        extraArgs:
          pod-recommendation-min-cpu-millicores: 15
          pod-recommendation-min-memory-mb: 50
          farlge: "$SECRET_TEST"
          v: 1
          prometheus-address: |
            http://prometheus-operator-prometheus.prometheus-operator.svc.cluster.local:9090
          storage: prometheus
      admissionController:
        enabled: true
        cleanupOnDelete:
          enabled: false
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 50m
            memory: 64Mi
```
```
